#!/bin/sh

#echo 'Installing...'
#sudo python ./setup.py install
#echo 'installation done.'

#pushd tests > /dev/null
#echo 'Testing...'
#python ./test.py
#echo 'testing done.'
#popd

echo 'Building...'
python ./setup.py sdist
python ./setup.py bdist_rpm
python ./setup.py bdist_wininst
echo 'building done.'

echo 'Uploading...'
pushd dist > /dev/null
for F in * ; do
  echo -n "  uploading $F..."
  ncftpput upload.sourceforge.net incoming "$F"
  echo "done."
done
echo 'uploading done'
