#! /bin/sh

"`dirname \"$0\"`"/svn2git \
   http://svn.colorstudy.com/SQLObject SQLObject-fullhistory &&

git init --bare SQLObject.git &&
cd SQLObject.git &&
echo "Bare SQLObject repository" >description &&
git fetch ../SQLObject-fullhistory master:master 1.5:1.5 1.6:1.6 1.7:1.7 tag 1.5.0b1 tag 1.5.0rc1 tag 1.5.0 tag 1.5.1 tag 1.5.2 tag 1.6.0a1 tag 1.6.0b1 tag 1.6.0 tag 1.7.0b1 &&

cd .. &&
git clone SQLObject.git SQLObject && rm -rf SQLObject.git &&
cd SQLObject && git remote rm origin && rmdir .git/refs/remotes/origin &&

echo "Development SQLObject repository" >.git/description &&
git branch --track 1.5 origin/1.5 &&
git branch --track 1.6 origin/1.6 &&
git branch --track 1.7 origin/1.7 &&

# Null merges
git checkout 1.6 && git merge --no-commit -s ours 1.5 &&
git checkout HEAD sqlobject/main.py && git commit &&

git checkout 1.7 && git merge --no-commit -s ours 1.6 &&
git checkout HEAD sqlobject/col.py && git commit &&

git checkout master && git merge --no-commit -s ours 1.7 &&
git checkout HEAD setup.cfg setup.py \
   sqlobject/__version__.py sqlobject/converters.py \
   sqlobject/tests/test_converters.py sqlobject/tests/test_datetime.py &&
git commit &&

exec vim .git/config
