#!/usr/bin/env python
import sys
import os
try:
    import sqlobject
except ImportError:
    try:
        here = __file__
    except NameError:
        here = sys.argv[0]
    updir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(here))),
        'sqlobject')
    if sys.path.exists(updir):
        sys.path.insert(0, updir)
    else:
        print 'I cannot find the sqlobject module'
        print 'If SQLObject is installed, you may need to set $PYTHONPATH'
        sys.exit(3)

from sqlobject.manager import command
command.the_runner.run(sys.argv)
        
