#! /bin/sh

build_docs() {
   git checkout "$1" &&
   ../build-docs &&
   rsync -ahP --del --exclude=/robots.txt docs/html/ ../SQLObject-docs/"$2"/
}

PROG_DIR="`dirname \"$0\"`" &&
cd "$PROG_DIR" &&
PROG_DIR="`pwd`" &&

cd "$PROG_DIR"/SQLObject &&
build_docs 3.7.1 &&
build_docs master devel &&
rm -rf docs/html &&

cd ../SQLObject-docs &&
exec sitemap_gen.py --config="$PROG_DIR"/sqlobject.org-sitemapconfig.xml
