#! /bin/sh

cd "`dirname \"$0\"`"/SQLObject &&
umask 022 &&
chmod -R a+rX . &&

../build-docs &&
../set-commit-date.py &&

python setup.py build_py &&
python setup.py register sdist upload --sign &&

for py in 2.6 2.7 3.4 3.5 3.6; do
   find build -name '*.py[co]' -delete &&
   python$py    -m compileall build &&
   python$py -O -m compileall build &&
   python$py setup.py bdist_egg upload --sign || exit 1
done

find build -name '*.py[co]' -delete &&
python setup.py bdist_wheel --universal upload --sign &&

if [ "$state" = final ]; then
   cp -a dist/* "$HOME"/tmp/ &&
   rsync -ahP4 dist/* frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/ &&
   rsync -ahP4 ANNOUNCE.rst frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/README.rst || exit 1
fi

exec rm -rf build dist docs/html SQLObject.egg-info
