#! /bin/sh

cd "`dirname \"$0\"`"/.. &&
umask 022 &&
chmod -R a+rX . &&

set-commit-date.py &&
devscripts/build-docs &&

python setup.py build_py &&
python setup.py build --executable '/usr/bin/env python' &&
python setup.py sdist &&

find build -name '*.py[co]' -delete &&
python setup.py bdist_wheel --universal &&

version=`python setup.py --version`
. devscripts/split_tag.sh &&
split_tag $version

if [ "$state" = final ]; then
   rsync -ahPv dist/* frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/ &&
   rsync -ahPv ANNOUNCE.rst frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/README.rst || exit 1
   devscripts/sftp-frs
fi &&

cd dist &&
if [ -f SQLObject-$version.tar.gz ]; then
    mv SQLObject-$version.tar.gz sqlobject-$version.tar.gz
fi &&
if [ -f SQLObject-$version-py2.py3-none-any.whl ]; then
    mv SQLObject-$version-py2.py3-none-any.whl \
       sqlobject-$version-py2.py3-none-any.whl
fi &&
cd .. &&

twine upload --disable-progress-bar --skip-existing dist/* &&
exec rm -rf build dist docs/html SQLObject.egg-info
