#! /bin/sh

cd "`dirname \"$0\"`"/.. &&
umask 022 &&
chmod -R a+rX . &&
find .git/objects -type f -exec chmod u=r,go= '{}' \+ &&

set-commit-date.py &&
devscripts/build-docs &&

python setup.py build_py &&
python setup.py build --executable '/usr/bin/env python' &&
python setup.py sdist &&

find build -name '*.py[co]' -delete &&
python setup.py bdist_wheel --universal &&

version=`python setup.py --version`
. devscripts/split_tag.sh &&
split_tag $version

if [ "$state" = final ]; then
   rsync -ahPv dist/* frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/ &&
   rsync -ahPv ANNOUNCE.rst frs.sourceforge.net:/home/frs/project/sqlobject/sqlobject/"$version"/README.rst || exit 1
   devscripts/sftp-frs
fi &&

twine upload --disable-progress-bar --skip-existing dist/* &&
exec rm -rf build dist docs/html sqlobject.egg-info
