#! /bin/sh

START_DIR="`pwd`"
CWD="$START_DIR"

while [ ! -f setup.py -a "$CWD" != / ]; do
   cd .. && CWD="`pwd`" || exit 1
done
if [ ! -f setup.py ]; then
   echo "Cannot find setup.py, abort" >&2
   exit 1
fi
SO_DIR="$CWD"

PYTHONPATH="$CWD"
export PYTHONPATH

TESTDB_URI="$1"
shift

cd "$START_DIR" &&
exec python"$PY_VER" `which pytest` $PYTEST_OPTIONS -D "$TESTDB_URI" "$@"
