#!/bin/sh

here=`pwd`
parent=`dirname $here`
echo "Adding $parent to \$PYTHONPATH"
export PYTHONPATH=$parent:$PYTHONPATH

NORMAL="Authors DeveloperGuide FAQ Inheritance News
        SQLBuilder SQLObject SelectResults TODO Versioning Views
        community download index links sqlobject-admin sqlobject-architecture"

for NAME in $NORMAL ; do
    if [ -e "$NAME.html" -a ! "$NAME.html" -ot "$NAME.txt" ] ; then
        echo "$NAME is up to date."
        continue
    fi
    echo "Building $NAME."
    rst2html.py --no-toc-backlinks --stylesheet=default.css --link-stylesheet \
        -- "$NAME.txt" > "$NAME.html"
done
